#define INSTRUCTION_LIST(_)                                                   \
    _(ADD, R, R, "ADD")                                                       \
    _(SUB, R, R, "SUB")                                                       \
    _(SLL, R, R, "SLL")                                                       \
    _(SLT, R, R, "SLT")                                                       \
    _(SLTU, R, R, "SLTU")                                                     \
    _(XOR, R, R, "XOR")                                                       \
    _(SRL, R, R, "SRL")                                                       \
    _(SRA, R, R, "SRA")                                                       \
    _(OR, R, R, "OR")                                                         \
    _(AND, R, R, "AND")                                                       \
    _(ADDI, I, I_ARITHMETIC, "ADDI")                                          \
    _(SLTI, I, I_ARITHMETIC, "SLTI")                                          \
    _(SLTIU, I, I_ARITHMETIC, "SLTIU")                                        \
    _(XORI, I, I_ARITHMETIC, "XORI")                                          \
    _(ORI, I, I_ARITHMETIC, "ORI")                                            \
    _(ANDI, I, I_ARITHMETIC, "ANDI")                                          \
    _(SLLI, I, I_ARITHMETIC, "SLLI")                                          \
    _(SRLI, I, I_ARITHMETIC, "SRLI")                                          \
    _(SRAI, I, I_ARITHMETIC, "SRAI")                                          \
    _(LB, I, I_LOAD, "LB")                                                    \
    _(LH, I, I_LOAD, "LH")                                                    \
    _(LW, I, I_LOAD, "LW")                                                    \
    _(LBU, I, I_LOAD, "LBU")                                                  \
    _(LHU, I, I_LOAD, "LHU")                                                  \
    _(JALR, I, I_JALR, "JALR")                                                \
    _(SB, S, S, "SB")                                                         \
    _(SH, S, S, "SH")                                                         \
    _(SW, S, S, "SW")                                                         \
    _(BEQ, B, B, "BEQ")                                                       \
    _(BNE, B, B, "BNE")                                                       \
    _(BLT, B, B, "BLT")                                                       \
    _(BGE, B, B, "BGE")                                                       \
    _(BLTU, B, B, "BLTU")                                                     \
    _(BGEU, B, B, "BGEU")                                                     \
    _(LUI, U, U_LUI, "LUI")                                                   \
    _(AUIPC, U, U_AUIPC, "AUIPC")                                             \
    _(JAL, J, J, "JAL")                                                       \
    _(NOP, NOP, NOP, "NOP")
